// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/supersupersimple/comment/ent/conf"
)

// ConfCreate is the builder for creating a Conf entity.
type ConfCreate struct {
	config
	mutation *ConfMutation
	hooks    []Hook
}

// SetPassword sets the "password" field.
func (cc *ConfCreate) SetPassword(s string) *ConfCreate {
	cc.mutation.SetPassword(s)
	return cc
}

// SetAllowOrigins sets the "allow_origins" field.
func (cc *ConfCreate) SetAllowOrigins(s []string) *ConfCreate {
	cc.mutation.SetAllowOrigins(s)
	return cc
}

// SetCookieSecret sets the "cookie_secret" field.
func (cc *ConfCreate) SetCookieSecret(s string) *ConfCreate {
	cc.mutation.SetCookieSecret(s)
	return cc
}

// SetLimitPerBatch sets the "limit_per_batch" field.
func (cc *ConfCreate) SetLimitPerBatch(i int) *ConfCreate {
	cc.mutation.SetLimitPerBatch(i)
	return cc
}

// SetNillableLimitPerBatch sets the "limit_per_batch" field if the given value is not nil.
func (cc *ConfCreate) SetNillableLimitPerBatch(i *int) *ConfCreate {
	if i != nil {
		cc.SetLimitPerBatch(*i)
	}
	return cc
}

// SetMaxLoopDepth sets the "max_loop_depth" field.
func (cc *ConfCreate) SetMaxLoopDepth(i int) *ConfCreate {
	cc.mutation.SetMaxLoopDepth(i)
	return cc
}

// SetNillableMaxLoopDepth sets the "max_loop_depth" field if the given value is not nil.
func (cc *ConfCreate) SetNillableMaxLoopDepth(i *int) *ConfCreate {
	if i != nil {
		cc.SetMaxLoopDepth(*i)
	}
	return cc
}

// SetHost sets the "host" field.
func (cc *ConfCreate) SetHost(s string) *ConfCreate {
	cc.mutation.SetHost(s)
	return cc
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (cc *ConfCreate) SetNillableHost(s *string) *ConfCreate {
	if s != nil {
		cc.SetHost(*s)
	}
	return cc
}

// SetTgBotURL sets the "tg_bot_url" field.
func (cc *ConfCreate) SetTgBotURL(s string) *ConfCreate {
	cc.mutation.SetTgBotURL(s)
	return cc
}

// SetNillableTgBotURL sets the "tg_bot_url" field if the given value is not nil.
func (cc *ConfCreate) SetNillableTgBotURL(s *string) *ConfCreate {
	if s != nil {
		cc.SetTgBotURL(*s)
	}
	return cc
}

// Mutation returns the ConfMutation object of the builder.
func (cc *ConfCreate) Mutation() *ConfMutation {
	return cc.mutation
}

// Save creates the Conf in the database.
func (cc *ConfCreate) Save(ctx context.Context) (*Conf, error) {
	cc.defaults()
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *ConfCreate) SaveX(ctx context.Context) *Conf {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *ConfCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *ConfCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cc *ConfCreate) defaults() {
	if _, ok := cc.mutation.LimitPerBatch(); !ok {
		v := conf.DefaultLimitPerBatch
		cc.mutation.SetLimitPerBatch(v)
	}
	if _, ok := cc.mutation.MaxLoopDepth(); !ok {
		v := conf.DefaultMaxLoopDepth
		cc.mutation.SetMaxLoopDepth(v)
	}
	if _, ok := cc.mutation.Host(); !ok {
		v := conf.DefaultHost
		cc.mutation.SetHost(v)
	}
	if _, ok := cc.mutation.TgBotURL(); !ok {
		v := conf.DefaultTgBotURL
		cc.mutation.SetTgBotURL(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *ConfCreate) check() error {
	if _, ok := cc.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`ent: missing required field "Conf.password"`)}
	}
	if _, ok := cc.mutation.AllowOrigins(); !ok {
		return &ValidationError{Name: "allow_origins", err: errors.New(`ent: missing required field "Conf.allow_origins"`)}
	}
	if _, ok := cc.mutation.CookieSecret(); !ok {
		return &ValidationError{Name: "cookie_secret", err: errors.New(`ent: missing required field "Conf.cookie_secret"`)}
	}
	if _, ok := cc.mutation.LimitPerBatch(); !ok {
		return &ValidationError{Name: "limit_per_batch", err: errors.New(`ent: missing required field "Conf.limit_per_batch"`)}
	}
	if _, ok := cc.mutation.MaxLoopDepth(); !ok {
		return &ValidationError{Name: "max_loop_depth", err: errors.New(`ent: missing required field "Conf.max_loop_depth"`)}
	}
	if _, ok := cc.mutation.Host(); !ok {
		return &ValidationError{Name: "host", err: errors.New(`ent: missing required field "Conf.host"`)}
	}
	if _, ok := cc.mutation.TgBotURL(); !ok {
		return &ValidationError{Name: "tg_bot_url", err: errors.New(`ent: missing required field "Conf.tg_bot_url"`)}
	}
	return nil
}

func (cc *ConfCreate) sqlSave(ctx context.Context) (*Conf, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *ConfCreate) createSpec() (*Conf, *sqlgraph.CreateSpec) {
	var (
		_node = &Conf{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(conf.Table, sqlgraph.NewFieldSpec(conf.FieldID, field.TypeInt64))
	)
	if value, ok := cc.mutation.Password(); ok {
		_spec.SetField(conf.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if value, ok := cc.mutation.AllowOrigins(); ok {
		_spec.SetField(conf.FieldAllowOrigins, field.TypeJSON, value)
		_node.AllowOrigins = value
	}
	if value, ok := cc.mutation.CookieSecret(); ok {
		_spec.SetField(conf.FieldCookieSecret, field.TypeString, value)
		_node.CookieSecret = value
	}
	if value, ok := cc.mutation.LimitPerBatch(); ok {
		_spec.SetField(conf.FieldLimitPerBatch, field.TypeInt, value)
		_node.LimitPerBatch = value
	}
	if value, ok := cc.mutation.MaxLoopDepth(); ok {
		_spec.SetField(conf.FieldMaxLoopDepth, field.TypeInt, value)
		_node.MaxLoopDepth = value
	}
	if value, ok := cc.mutation.Host(); ok {
		_spec.SetField(conf.FieldHost, field.TypeString, value)
		_node.Host = value
	}
	if value, ok := cc.mutation.TgBotURL(); ok {
		_spec.SetField(conf.FieldTgBotURL, field.TypeString, value)
		_node.TgBotURL = value
	}
	return _node, _spec
}

// ConfCreateBulk is the builder for creating many Conf entities in bulk.
type ConfCreateBulk struct {
	config
	err      error
	builders []*ConfCreate
}

// Save creates the Conf entities in the database.
func (ccb *ConfCreateBulk) Save(ctx context.Context) ([]*Conf, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Conf, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConfMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *ConfCreateBulk) SaveX(ctx context.Context) []*Conf {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *ConfCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *ConfCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
