// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package adminpages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/supersupersimple/comment/app/model"
	"github.com/supersupersimple/comment/app/templates/admin/admincomponents"
)

func Setup(pageVals *model.AdminPageVals) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = Base(pageVals).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = admincomponents.Header().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form action=\"/admin/setup\" method=\"post\" class=\"mx-auto max-w-lg\"><label class=\"form-control w-full \"><input type=\"hidden\" name=\"csrf_token\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(pageVals.CsrfToken)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `admin/adminpages/setup.templ`, Line: 13, Col: 68}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"><div class=\"label\"><span class=\"label-text\">Host</span></div><input name=\"host\" type=\"text\" class=\"input input-bordered w-full\" placeholder=\"\"><div class=\"label\"><span class=\"label-text\">Name</span></div><input name=\"name\" type=\"text\" class=\"input input-bordered w-full\" placeholder=\"\" required><div class=\"label\"><span class=\"label-text\">Password</span></div><input name=\"password\" type=\"password\" class=\"input input-bordered w-full\" value=\"\" required><div class=\"label\"><span class=\"label-text\">Allow Origins (Each line represents a host)</span></div><textarea name=\"allow_origins\" class=\"textarea textarea-bordered h-24\" placeholder=\"\" required></textarea><div class=\"label\"><span class=\"label-text\">Default root comments per batch</span></div><select name=\"limit_per_batch\" class=\"select select-bordered\"><option value=\"5\" selected>5</option> <option value=\"10\">10</option> <option value=\"15\">15</option> <option value=\"20\">20</option></select><div class=\"label\"><span class=\"label-text\">Default loading comments depth</span></div><select name=\"max_loop_depth\" class=\"select select-bordered\"><option value=\"3\" selected>3</option> <option value=\"4\">4</option> <option value=\"5\">5</option></select><div class=\"label\"><span class=\"label-text\">Telegram bot url</span></div><input name=\"tg_bot_url\" type=\"text\" class=\"input input-bordered w-full\" placeholder=\"\"> <button class=\"btn mt-4\" type=\"submit\" value=\"Create\">Create</button></label></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
