// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Conf is the predicate function for conf builders.
type Conf func(*sql.Selector)

// Page is the predicate function for page builders.
type Page func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
